Use const since local variable is never mutated
Spotted while trying this project out with the latest Zig `master` (`0.12.0-dev.1676+40b8c993f`)

```
src/main.zig:35:9: error: local variable is never mutated
    var rtn = try allocator.alloc(@TypeOf(data[0]), data.len);
        ^~~
src/main.zig:35:9: note: consider using 'const'
src/main.zig:45:9: error: local variable is never mutated
    var intermediate = try allocator.alloc(IdxT, data.len);
        ^~~~~~~~~~~~
src/main.zig:45:9: note: consider using 'const'
src/main.zig:43:9: error: local variable is never mutated
    var rtn = try allocator.alloc(@TypeOf(data[0]), data.len);
        ^~~
src/main.zig:43:9: note: consider using 'const'
src/main.zig:93:9: error: local variable is never mutated
    var data = try allocator.alloc(f64, 10000);
        ^~~~
src/main.zig:93:9: note: consider using 'const'
src/main.zig:92:9: error: local variable is never mutated
    var rand = ri.random();
        ^~~~
```